# https://travis-ci.org/
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: "node_modules/.bin/testem launchers"
script: "npm run verify"
addons:
  firefox: '38.0'
